# VS Code REST Client 参数
#@baseUrl=http://localhost:9000/api/v1
#@username=123
#@password=123

# 认证
POST {{baseUrl}}/auth
Content-Type: application/json

{
  "open_id": "{{open_id}}",
  "minapp_id": {{minapp_id}}
}

> {% client.global.set("cookie", response.headers.valueOf("Set-Cookie"));%}

###

# 学号密码认证
POST {{baseUrl}}/auth?school=gzhu
Content-Type: application/x-www-form-urlencoded

username={{username}}&password={{password}}


###

# 课表查询
POST {{baseUrl}}/jwxt/course
Content-Type: application/x-www-form-urlencoded

username={{username}}&password={{password}}&year_sem=2019-2020-2&first_monday=2020-03-02


###

# 成绩查询
POST {{baseUrl}}/jwxt/grade
Content-Type: application/json

{
  "username": "{{username}}",
  "password": "{{password}}"
}


###

# 成绩排名
GET {{baseUrl}}/jwxt/rank?username={{username}}
Content-Type: application/x-www-form-urlencoded
Cookie: {{cookie}}

###

# 空教室查询
POST {{baseUrl}}/jwxt/classroom
Content-Type: application/x-www-form-urlencoded

username={{username}}&password={{password}}&xqh_id=1&xnm=2019&xqm=3&cdlb_id=&qszws=&jszws=&lh=&cdmc=&zcd=17&xqj=6&jcd=1&queryModel.currentPage=1


###

# 学业情况
POST {{baseUrl}}/jwxt/achieve
Content-Type: application/x-www-form-urlencoded

username={{username}}&password={{password}}


###

# 考试查询
POST {{baseUrl}}/jwxt/exam
Content-Type: application/x-www-form-urlencoded

username={{username}}&password={{password}}&year_sem=2019-2020-1


###

# 全校课表查询/导出
#POST {{baseUrl}}/jwxt/all-course?year=2019&sem=2&page=1&count=15&action=export
POST {{baseUrl}}/jwxt/all-course?year=2019&sem=2&page=1&count=30
Content-Type: application/x-www-form-urlencoded

username={{username}}&password={{password}}


###

# 图书查询
GET {{baseUrl}}/library/search?query=python&page=1
Content-Type: application/x-www-form-urlencoded

###

# 馆藏查询
GET {{baseUrl}}/library/holdings?id=1000024660&source=bibliosus
Content-Type: application/x-www-form-urlencoded

###

# CET验证码获取，captcha留空
GET {{baseUrl}}/cet?id=准考证&name=姓名captcha=
Content-Type: application/x-www-form-urlencoded

###

# CET查询
GET {{baseUrl}}/cet?id=准考证&name=姓名captcha=验证码
Content-Type: application/x-www-form-urlencoded

###



