# 认证
POST {{baseUrl}}/auth
Content-Type: application/json

{
  "open_id": "{{open_id}}",
  "minapp_id": {{minapp_id}}
}

> {% client.global.set("cookie", response.headers.valueOf("Set-Cookie"));%}

###


# 模糊搜索
GET {{baseUrl}}/_QUERIES/topic/v_topic_search?match=求助
Content-Type: application/x-www-form-urlencoded
Cookie: {{cookie}}

###

# 通知查询
GET {{baseUrl}}/postgres/public/t_notify?status=0&_order=created_at
Content-Type: application/x-www-form-urlencoded
Cookie: {{cookie}}

###

# 主题查询
GET {{baseUrl}}/gzhupi/public/v_topic?id=$eq.251
Content-Type: application/x-www-form-urlencoded
Cookie: {{cookie}}

###

# 留言查询
GET {{baseUrl}}/gzhupi/public/v_discuss?id=$eq.220
Content-Type: application/x-www-form-urlencoded
Cookie: {{cookie}}

###

